pipeline {
    agent any
    stages {
        stage("Verify Tooling") {
            steps {
                sh '''
                  docker version
                  docker info
                  docker compose version 
                  curl --version
                '''
            }
        }
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Git Checkout') {
            steps {
                checkout scmGit(
                branches: [[name: 'main']],
                userRemoteConfigs: [[url: 'https://github.com/ycherkas/devops.git']])
            }
        }
        stage('Prune Docker Data') {
            steps {
                sh 'docker system prune -a --volumes -f'
            }
        }
        stage('Start Container') {
            steps {
                sh '''
                    #!/bin/bash
                    cd lab1
                    docker compose up -d --no-color --wait
                    docker compose ps
                '''
            }
        }
    }
    post {
        always {
            sh '''
                #!/bin/bash
                cd lab1
                docker compose down --remove-orphans -v
                docker compose ps
            '''
        }
    }
}